---
title: "Analysis 2.0"
author: "AMH"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Amy's packages and working directory
```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)

setwd("C:/Users/hrusk/Dropbox (Smithsonian)/2021_SummerInterns/AM")

dat <- read.csv("Heat_herbivory_alldata.csv")

dat2 <- read.csv("Heat_herbivory_alldata_v2.csv")

```


Annika just messin' around 
```{r}
shawty <- 3*7*16
print(shawty)
```

Annika's packages and working directory
```{r}

```

Data wrangling/cleaning
```{r}
##change value of first cell in datasheet#
dat[1, 1] = "8-Jul"


##remove spaces from dataset#
dat2 <- dat %>%
  mutate(across(where(is.factor), str_remove_all, pattern = fixed (" ")))

#create dataset for height graphing and analysis#

height <- dat2 %>%
  select(Date, Species, Temperature, Plant_number, Height_cm)
height$Height_cm <- as.numeric(height$Height_cm
                              )

height2 <- na.omit(height)

#test height_cm is numeric and set to numeric#
is.numeric(height2$Height_cm)
height2$Height_cm <- as.numeric((height2$Height_cm))

#height last day#
height3 <- height2 %>%
  filter(Date == "9-Aug")
height3 <- na.omit(height3)
height3$Height_cm <- as.numeric(height3$Height_cm)

#height first day#
height4 <- height %>%
  filter(Date == "8-Jul")
height4$Height_cm <- as.numeric((height4$Height_cm))

#merge height of last and first date and create a new column for change in height#
height5 <- merge(height3, height4, by = "Plant_number")
height6 <- na.omit(height5)
height6$Height_cm.x <- as.numeric((height6$Height_cm.x))
height6$Height_cm.y <- as.numeric((height6$Height_cm.y))


height7 <- height6 %>% 
  mutate(delta= height6$Height_cm.x - height6$Height_cm.y)

```

BarStats Function
```{r}

barGraphStats <- function(data, variable, byFactorNames) {
  count <- length(byFactorNames)
  N <- aggregate(data[[variable]], data[byFactorNames], FUN=length)
  names(N)[1:count] <- byFactorNames
  names(N) <- sub("^x$", "N", names(N))
  mean <- aggregate(data[[variable]], data[byFactorNames], FUN=mean)
  names(mean)[1:count] <- byFactorNames
  names(mean) <- sub("^x$", "mean", names(mean))
  sd <- aggregate(data[[variable]], data[byFactorNames], FUN=sd)
  names(sd)[1:count] <- byFactorNames
  names(sd) <- sub("^x$", "sd", names(sd))
  preSummaryStats <- merge(N, mean, by=byFactorNames)
  finalSummaryStats <- merge(preSummaryStats, sd, by=byFactorNames)
  finalSummaryStats$se <- finalSummaryStats$sd / sqrt(finalSummaryStats$N)
  return(finalSummaryStats)
  
}
```


```{r}
##Creating colourblind palette###
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

##saved graph as variable to edit theme below##
g1 <- ggplot(data = barGraphStats(data = height2, variable = "Height_cm", byFactorNames = c("Species", "Temperature")), aes(x=Species, y=mean, fill = Temperature)) +
    geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
    xlab("Plant Species") + ylab("Plant Height (cm)") +
    scale_fill_manual(values = cbPalette) 

##setting theme to remove background grid and add axis lines##    
g1 + theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), text = element_text(size = 16),axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))


```


Height on final day graph
```{r}
##saved graph as variable to edit theme below##
g2 <- ggplot(data = barGraphStats(data = height3, variable = "Height_cm", byFactorNames = c("Species", "Temperature")), aes(x=Species, y=mean, fill = Temperature)) +
    geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
    xlab("Plant Species") + ylab("Plant Height (cm)") +
    scale_fill_manual(values = cbPalette) 

##setting theme to remove background grid and add axis lines##    
g2 + theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), text = element_text(size = 16),axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))
```
Delta height graph
```{r}
g2 <- ggplot(data = barGraphStats(data = height7, variable = "delta", byFactorNames = c("Species.x", "Temperature.x")), aes(x=Species.x, y=mean, fill = Temperature.x)) +
    geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
    xlab("Plant Species") + ylab("Change in Plant Height (cm)") +
    scale_fill_manual(values = cbPalette) 

##setting theme to remove background grid and add axis lines##    
g2 + theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), text = element_text(size = 16),axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))


```
Stats on plant height
```{r}

#test for normality, definitly not normal#
shapiro.test(height2$Height_cm)
ggqqplot(height2$Height_cm)

##packages for glm, glmms#
library(lme4)
library(nlme)
library(lattice)
library(effects)

mod0 <- lm(Height_cm ~ Species*Temperature, data = height2)
anova(mod0)#statisical test 

mod1 <- lme(Height_cm ~ Temperature*Species, random = ~1|Date, data = height2)
anova(mod1)

mod2 <- lm(Height_cm ~ Temperature*Species, data = height3)
anova(mod2)

mod3 <- lm(delta ~ Temperature.x*Species.x, data = height7)
anova(mod3)

```


